"""add_sanctions_sync_audits_table

Revision ID: 67e19b9e1c24
Revises: ede3be15cf82
Create Date: 2026-07-15 22:15:55.361565

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e19b9e1c24'
down_revision: str | None = 'ede3be15cf82'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_sync_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sync_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_removed', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('sync_duration_seconds', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sanctions_sync_audits')
    # ### end Alembic commands ###
