"""initial schema

Revision ID: 83bbeee0342b
Revises: 
Create Date: 2026-07-15 03:47:10.716028

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bbeee0342b'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('monitoring_status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('company_directors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_directors_company_id'), 'company_directors', ['company_id'], unique=False)
    op.create_table('monitoring_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_runs_company_id'), 'monitoring_runs', ['company_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_company_id'), 'timeline_events', ['company_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_company_id'), 'human_reviews', ['company_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_company_id'), 'news_articles', ['company_id'], unique=False)
    op.create_table('risk_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_reports_company_id'), 'risk_reports', ['company_id'], unique=False)
    op.create_table('sanction_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('list_name', sa.String(length=1000), nullable=False),
    sa.Column('matched_name', sa.String(length=255), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanction_matches_company_id'), 'sanction_matches', ['company_id'], unique=False)
    op.create_table('sar_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sar_reports_company_id'), 'sar_reports', ['company_id'], unique=False)
    op.create_table('watchlist_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('monitoring_run_id', sa.Uuid(), nullable=True),
    sa.Column('watchlist_name', sa.String(length=1000), nullable=False),
    sa.Column('matched_name', sa.String(length=255), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_matches_company_id'), 'watchlist_matches', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_matches_company_id'), table_name='watchlist_matches')
    op.drop_table('watchlist_matches')
    op.drop_index(op.f('ix_sar_reports_company_id'), table_name='sar_reports')
    op.drop_table('sar_reports')
    op.drop_index(op.f('ix_sanction_matches_company_id'), table_name='sanction_matches')
    op.drop_table('sanction_matches')
    op.drop_index(op.f('ix_risk_reports_company_id'), table_name='risk_reports')
    op.drop_table('risk_reports')
    op.drop_index(op.f('ix_news_articles_company_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_human_reviews_company_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_timeline_events_company_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_monitoring_runs_company_id'), table_name='monitoring_runs')
    op.drop_table('monitoring_runs')
    op.drop_index(op.f('ix_company_directors_company_id'), table_name='company_directors')
    op.drop_table('company_directors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
