"""add_company_news_scheduling_fields

Revision ID: 9282248680e4
Revises: 67e19b9e1c24
Create Date: 2026-07-15 22:45:03.814944

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9282248680e4'
down_revision: str | None = '67e19b9e1c24'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('news_monitoring_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('companies', sa.Column('news_monitoring_interval_minutes', sa.Integer(), nullable=False, server_default='1440'))
    op.add_column('companies', sa.Column('last_news_check_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_news_check_at')
    op.drop_column('companies', 'news_monitoring_interval_minutes')
    op.drop_column('companies', 'news_monitoring_enabled')
    # ### end Alembic commands ###
