"""add company audit state table

Revision ID: ede3be15cf82
Revises: 83bbeee0342b
Create Date: 2026-07-15 06:59:20.551618

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede3be15cf82'
down_revision: str | None = '83bbeee0342b'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_audit_states',
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('last_risk_level', sa.String(length=20), nullable=False),
    sa.Column('last_sanction_count', sa.Integer(), nullable=False),
    sa.Column('last_sanction_ids', sa.JSON(), nullable=False),
    sa.Column('last_news_count', sa.Integer(), nullable=False),
    sa.Column('last_news_hash', sa.String(length=64), nullable=True),
    sa.Column('last_entity_confidence', sa.Float(), nullable=False),
    sa.Column('last_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sar_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sar_risk', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_audit_states')
    # ### end Alembic commands ###
